name: Lint and test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  DB_USER: postgres
  DOCKER_POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Setup db
        run: npm run setup-db
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
